### ISSUE TITLE
Error handling needs work when user enters a URL for importing a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1384]
1. If the URL does not reference a repo on door43, the message returned is:
![image](https://cloud.githubusercontent.com/assets/8171759/25597864/edcf286c-2e96-11e7-92d1-02da4f431b77.png)

2. If the URL does reference a repo, but not a project (e.g. https://git.door43.org/qa99/), no error is returned and nothing happens. Nothing is added to the console log either.

3. If there is no Internet connection, no error message is returned and nothing happens.

**Comment by cdwhitfield73** [comment]
I have some of the basic options covered, plus a generic message.  Let me know if we need more details.

**Comment by cckozie** [comment]
A generic "Problem occurred during import" is not sufficient. We need to always tell the user whatever details we know about the problem. 
If the Internet is not available, we need to tell them so with a standardized message.
If the URL entered is not for a door43 project repo, we should give them a message similar to "The URL does not reference a valid project."
The Import & Select button should be disabled until the user enters a URL.

**Comment by cdwhitfield73** [comment]
I believe the above scenarios have been addressed.  There is one custom message for no internet or lost internet and another custom message if the URL does not exist or is not a valid project.  There is also still the generic message if any other error occurs.  And I added the disabling of the button when there is no text in the box.  Good idea!

**Comment by cckozie** [comment]
Imported https://git.door43.org/qa98/qaa-x-1560c6_tit_text_reg
Did not choose a tool, but instead went back to the Import Online Project screen
The URL was still showing in the text box. I erased the project info so that the URL was now https://git.door43.org/qa98/
Clicked the Import and Select button and the app appeared to locked up. None of the buttons would do anything and clicking off of the modal did not do anything. I was able to enable the developer tools from the Window menu (on my Mac), and after about 15 seconds the console opened up and the tC app went to the Welcome screen.
Here's the text from the console
[log1.txt](https://github.com/unfoldingWord-dev/translationCore/files/984817/log1.txt)
:

Restarted tC, went to the Import Online Project screen, entered https://git.door43.org/qa98/ in the URL field and clicked Import and Select. The spinner spins forever. No error message. I have the same result if I use https://git.door43.org/ as the URL.
Here's the text from the console:
[log2.txt](https://github.com/unfoldingWord-dev/translationCore/files/984824/log2.txt)

It does appear to work properly if there is no Internet connection and if the URL is something other than door43.

**Comment by cdwhitfield73** [comment]
Yes, trying to download those URL's does make quite a mess!  Added a regex expression to verify that the URL is a complete Door43 URL with a project before attempting to download.
