### ISSUE TITLE
More problems with USFM import

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2714]
tC does not properly allow for or correctly interpret various legitimate content in USFM files.
These examples came from this file:
[en_LUK_Luke.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1315157/en_LUK_Luke.usfm.zip)
(OPEN THIS COMMENT BOX FOR EDITING IN ORDER TO SEE THE EXAMPLE FOR #2.)
1. Properly deal with inline verse markers: e.g. \v 1 Many have tried to set in order a narrative about those matters that have been fulfilled among us, \v 2 just as they handed them to us, who from the beginning have been eyewitnesses and servants of the message. \v 3 So to me also it seemed good—having accurately investigated the course of all these things from the beginning— to write an orderly account for you, most excellent Theophilus. \v 4 This is so that you might know the truth about the things that you were taught.

2. [DO NOT FIX] Ignore (at least for validation and display) paragraph formatting markers: e.g. <para style="q1"> \v 54 He has given help to Israel his servant,</para> <para style="q1">so as to remember to show mercy</para> <para style="q1"> \v 55 (as he said to our fathers) to Abraham and his descendants forever."</para>
\s5
<para style="p"> \v 56 Mary stayed with Elizabeth about three months and then returned to her house.</para> <para style="p"> \v 57 Now the time had come for Elizabeth to deliver her baby and she gave birth to a son. \v 58 Her neighbors and her relatives heard that the Lord had shown his great mercy to her, and they rejoiced with her.</para>

3. Properly interpret chapter markers with leading zeros: e.g. 
\s5
\c 01
\cl Chapter 1

4. tC reports that 1:81 and 1:82 are missing verses, but Luke 1 only has 80 verses.

**Comment by PhotoNomad0** [comment]
For the first step of this issue, I am currently looking at changing usfm-js library.  Related to items above:
1. Looks like it is already fixed (added unit test to library and it properly splits out embedded verses)
2. A couple issues:
   *  It looks like we could preserve usfm markers by appending to existing verses.  Would that cause problems with the tools having embedded json in the verse?
   * Also it looks like we need to preserve chapter front matter.  Would it cause problems if I added a verse named 'front'?
3. Looks like a simple issue of removing leading zeroes from numbers.

**Comment by richmahn** [comment]
Isn't \v 0 used for front matter?

**Comment by PhotoNomad0** [comment]
> Isn't \v 0 used for front matter?

Not seeing any verse 0 being created in the USFM import library, all USFM between chapter marker and first verse seem to be thrown away.  On Door43 front matter would be in file front.txt.  But it looks like verse 0 would work with USFM export and may be less problem for tC.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [4] - Fix USFM parsing - Items 1 and 3
- [ ] [4] - Unit Testing
- [ ] [2] - Review PR
- [ ] [2] - Review PR #2

**Comment by PhotoNomad0** [comment]
#### Notes:
- Item 1 is already partially done.  Inline verse content is preserved, but preserving formatting will need new verse objects for USFM 3
- Item 2 is future - we currently don't support USX.
- Item 3 already fixed in develop.
- Item 4 is fixed in different PR in tc resources.

**Comment by PhotoNomad0** [comment]
Resolution as above.

**Comment by cckozie** [comment]
1. There is still a problem with inline verse markers. This may be the case only where there is also a  para style="p" string involved. See in the Luke project referenced in the first comment, the usfm text for 4:39 is: (open this comment for editing to see the complete text)
\s5
<para style="p"> \v 38 Then Jesus left the synagogue and entered into the house of Simon. Now Simon's mother-in-law was suffering with a high fever, and they pleaded with him on her behalf. \v 39 So he stood over her and rebuked the fever, and it left her. Immediately she got up and started serving them.</para>
In tC, the verse 39 text shows as:
![image](https://user-images.githubusercontent.com/8171759/34490026-0b340ce6-efa4-11e7-9523-a45be4dd3e52.png)

@benjore Is this something we care about at this point?

Issues 3 and 4 have been fixed.

**Comment by cckozie** [comment]
The item just above is due to old project creating USX which we're not supporting at this time.
