### ISSUE TITLE
tW percent complete shows 99% even though all checks have been completed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4416]
## Story

As a user, I want the tool card to say 100% when I have completed all the checks so that I am not misled that there is still more work to be done.

v0.9.0
[en_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1969055/en_tit.zip)
I started with a project having no selections. I made a selection for every check, but the percent complete only shows 99% on both the Tools page and Home page. I do see the check mark on every check, and there are no bookmarks.

**Comment by bspidel** [comment]
This bug is fixed as part of #5335 which is merged with 1.0.2

**Comment by cckozie** [comment]
The project attached to the first comment still shows 99% in 1.0.2 (5ebb84f)

**Comment by bspidel** [comment]
The problem is not that the app cannot display 100%. The problem has two parts. First, There is an error in the ugnt in that in one version there were 2 keywords live and life but now there is a combined keyword containing life and live. There is no longer a separate article for live.

The second part of the problem is that some projects have an index that reflects the former version whose index contains live and life. This causes the app to expect an extra check which the user can not see.

**Comment by bspidel** [comment]
Koz agreed to close this story as the problem is not the ability to indicate 100% progress. A new story #5354 has been issued to upgrade project migrations.
