### ISSUE TITLE
Cannot load project in wA in v1.2

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5860]
1.2.0 (368d706)
[46-ROM.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2927263/46-ROM.usfm.zip)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/b12054d5-3e59-4c07-b86a-df16693e2c49)

**Comment by mannycolon** [comment]
@cckozie I was able to load this project with the wA tool. It may have been fixed along the way. Please retest.

**Comment by cckozie** [comment]
@mannycolon In 1.2.0 (3fa53ee) that Romans project still won't load in wA for me. Neither will this one:
[en_ult_act_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2963016/en_ult_act_book.zip) Have tried a few others including Ruth, and so far the only one that loads without the error is a Titus project.
Here's the full log:
[console.log](https://github.com/unfoldingWord-dev/translationCore/files/2963017/console.log)

**Comment by cckozie** [comment]
Well, I'm not sure what's changed, but now the Romans project and the Ruth project both do load properly in wA. However, the Acts project from the above comment still fails, as does the project at https://git.door43.org/lrsallee/en_ult_rut_book. (I think the Acts project was imported from Door43 using v1.1.3.)

**Comment by mannycolon** [comment]
ok thanks

**Comment by mannycolon** [comment]
Tested on 313e103 (v1.2.0)

**Comment by cckozie** [comment]
1.2.0 (ddfe57a)
All of the referenced projects do open in wA. However, when selecting the Acts project, it takes 90 seconds  before the Tools page is displayed. I'll watch for this and write it up elsewhere if it is not fixed after merging in the 1.1.3 fixes.
