### ISSUE TITLE
Change of locale is not always universally effective

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5898]
1.1.3 (e1fae24) and 1.2.0 (368d706)

Start with the English locale
Load a project in tW
Change the locale to Hindi
Note that the change is effective immediately
Exit to the Projects page
Change the locale back to English
ISSUE 1: Note that the 'last used time' is still in Hindi
Load the same project again in tW
ISSUE2: Note that tools UI is still in Hindi, but the menu bar is now in English

**Comment by cckozie** [comment]
2.0.0 (15e3755) 
Issue 1 above has been fixed.
Issue 2 is worse. Now everything in tW, except for the menu bar, stays in Hindi. It is broken the same way in all of the tools.
![Screen Shot 2019-09-12 at 10 41 23 AM](https://user-images.githubusercontent.com/8171759/64799335-29f92200-d54a-11e9-8a41-efd3ea0d1f1b.jpg)

**Comment by PhotoNomad0** [comment]
Note: have fix now for WA, but other tools still have some failure scenarios.

**Comment by PhotoNomad0** [comment]
This is working now for me in translationCore 2.1.0 (0a80f05).

**Comment by cckozie** [comment]
Issues 1 and 2 appear to both be fixed in 2.1.0 (0a80f05)

**Comment by elsylambert** [comment]
Looks good in 2.1.0 (d0a11e7)
