### ISSUE TITLE
Problems with 1.1.2 projects after upgrading to 1.1.3

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5959]
These 2 usfm projects were downloaded on 4/2/19 from https://git.door43.org/unfoldingWord/en_ult/

[57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3045734/57-TIT.usfm.zip)
[08-RUT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3045735/08-RUT.usfm.zip)

I imported them using tC 1.1.2
When loaded in wA I noticed that there were a lot of asterisks in the scripture pane
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/75803491-df08-4521-b01d-6bd689f620ff)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/23168483-dff6-4af0-a92b-1f577a265628)
I then upgraded to tC 1.1.3 (3f886e6) and loaded the two projects in wA
The text in the scripture pane remains the same (asterisks still there)

When the projects are imported directly into tC 1.1.3, they look correct in the scripture pane.

When the projects are reimported over the existing "bad" ones, the scripture pane is now correct. In the Ruth project, all of the alignments are fixed and the wA shows 100% complete, although all verses still show the broken link icon.

**Comment by PhotoNomad0** [comment]
@cckozie - it's looking like a bug with 1.1.2 USFM import.  ~Seems like it would be using same code as 1.1.3~.  Looking into the timeline of when we made changes to USFM format.

**Comment by PhotoNomad0** [comment]
Note:
- 1.1.2 is using usfm-js 1.0.12 and word-aligner 0.2.10
- 1.1.3 is using usfm-js 2.0.0 and word-aligner 0.2.13

looking into the differences.

**Comment by PhotoNomad0** [comment]
@cckozie @benjore - I have confirmed the usfm import bug in 1.1.2 dealing with the new USFM markers format (the `\zaln-s` terminator).  Think we need to get 1.1.3 out soon with the usfm fixes it has.

**Comment by PhotoNomad0** [comment]
@cckozie - it looks like this was fixed a long time ago.

**Comment by cckozie** [comment]
After importing the attached projects in 1.1.2 and then upgrading to 2.1.0 (0a80f05), both projects are still showing all of the asterisks in the scripture pane.
![image](https://user-images.githubusercontent.com/8171759/69673727-9ae7aa80-1060-11ea-975b-b5fcd13f6c2e.png)

**Comment by PhotoNomad0** [comment]
Will double check. But I think those USFM Projects were broken.

**Comment by PhotoNomad0** [comment]
@cckozie - OK now I remember the problem, the projects are correct in the valid USFM3 syntax (our original syntax was not valid USFM3).  The problem is that 1.1.2 is not forward compatible with the corrected USFM3 syntax that we use for alignments.  There is not a way to fix 1.1.2.  The only way to handle the path you suggest is to do a migration.  But there is not an easy way to do this detection of the use case of importing a newer format into an older app version.  Migrating that could cause a new set of problems in the future, since we would have to look for asterix and remove them hoping not to cause trouble.

Would recommend not doing anything about this since 1.1.2 is such an old version. And the recommendation to the user would be if they saw this problem would be to update tC and then do the USFM import again.  Trying to mitigate this through all possible upgrade paths would be very time consuming (e.g. 1.1.2 -> 1.1.3 -> 2.0.0 -> 2.1.0 -> 2.2.0, etc.) and could introduce new problems.

**Comment by cckozie** [comment]
I'm closing this based on McLeans comment and the fact that we've had no field reports of the problem.
